name: Deploy to Itch.io
on:
  workflow_call:
    secrets:
      BUTLER_API_KEY:
        required: true
      ITCH_USERNAME:
        required: true
      ITCH_GAME_ID:
        required: true

  workflow_dispatch:

env:
  ITCH_USERNAME: digx7
  ITCH_GAME_ID: treasure-hunt-post-game-jam


jobs:
  deployToItch:
    name: Upload to Itch ${{ matrix.build }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - HTML5/Playable in browser
        build:
          - WebGL
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.build }}
          path: build/${{ matrix.build }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ./build/${{ matrix.build }}
          itchUsername: ${{ secrets.ITCH_USERNAME }}
          itchGameId: ${{ secrets.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}