name: Deploy to Itch.io
on:
  workflow_call:
    secrets:
      BUTLER_API_KEY:
        required: true
      ITCH_USERNAME:
        required: true
      ITCH_GAME_ID:
        required: true

  workflow_dispatch:


jobs:
  deployToItch:
    name: Upload to Itch ${{ matrix.build }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - HTML5/Playable in browser
        build:
          - WebGL
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: Build-${{ matrix.build }}
          path: build/${{ matrix.build }}
      - uses: Oval-Tutu/publish-to-itch-with-butler@v1
        with:
          api-key: ${{ secrets.BUTLER_API_KEY }}
          itch_user: ${{ secrets.ITCH_USERNAME }}
          itch_game: ${{ secrets.ITCH_GAME_ID }}
          channel: ${{ matrix.channel }}
          package: ./build/${{ matrix.build }}/
          version: ${{ github.ref_name }}